### ISSUE TITLE
Dépôt de photo salle de réunion

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#24]
Dans une salle de réunion fixe:

- [x] Préparer un jeu de photos mettant en valeur des personnes autour d'une table de réunion, avec de la variété dans le comptage (de 0 à 7 par exemple)
- [x] Les packager au sein d'un script de simulation "reunion"

cf #6

**Comment by adriens** [comment]
Hello @gbertherat peux-tu stp me dropper sur ce ticket quellques photos normales et en mode debug de la salle dé rérunion flamboyant stp ?

**Comment by gbertherat** [comment]
@adriens 
[Normal.tar.gz](https://github.com/adriens/person-counter-api/files/5668667/Normal.tar.gz)
[Debug.tar.gz](https://github.com/adriens/person-counter-api/files/5668665/Debug.tar.gz)
