### ISSUE TITLE
Bench et optimisation

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#26]
# Objectif

Pour un modèle et un moteur fixe, mesurer la qualité de l'analyse d'un comptage de personnes sur une scène fixe, mais dont on dégradera progressivement la qualité.
L'objectif est de trouver une définition optimale, par exemple pour les IoT.

#  Métriques/datas à produire

Choisir une photo fixe en input, en paramètre, puis, produire un [csv](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/rendering-csv-and-tsv-data) avec les champs suivants:

- nom-photo
- taille-photo (bytes)
- définition de l'image (dpi)
- pourcentage de certitude exigé minimal
- nb. personnes détectées
- pourcentage de certitude minimal analysé
- pourcentage de certitude maximal analysé
- temps de processing (ms.)
- le nombre réel de personnes (détecté par un humain): cette valeur est donc fixe, passée en argument du programme qui génère ce fichier

sur cette même photo, itérer sur:

- définition (définition originale/max à la plus médiocre)
- pourcentage de certitude min (de 50% à 100% par tranches de 5%)

En sortie, générer un unique csv sur lequel nous pourrons tourner les algos d'optimisation.

# NB 

Ce programme en python sera utilisé comme outil de tuning de la solution. Je propose de le coder en python, comme un script à part.

**Comment by adriens** [comment]
Excellent, on va pouvir mettre ça en valeur maintenant. Tu peux dropper le csv de sotie dans ce ticket avec les images générées dégradeées ?

**Comment by gbertherat** [comment]
[benchmark.zip](https://github.com/adriens/person-counter-api/files/5557540/benchmark.zip)
[images.zip](https://github.com/adriens/person-counter-api/files/5557541/images.zip)

**Comment by gbertherat** [comment]
@adriens Big benchmark:
[Benchmark API.xlsx](https://github.com/adriens/person-counter-api/files/5563173/Benchmark.API.xlsx)
