### ISSUE TITLE
BUILD et run de l'api sur raspberry

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#33]
valider que sur rpi:

- [ ] Le code compile bien
- [ ] Depuis le jar on peut démarrer et utiliser l'api (avec `mvn` et `java -jar`
- [ ] Créer une image Docker dédiée sur Docker via un DockerFile dédié à rpi et la démarrer/tester

# NB

Dans une section dédiée au rpi dans README, donner le code qui a permis de dérouler les actions en question

# Ressource

Checker l'image java dédiée rpi et maintenue https://hub.docker.com/r/balenalib/raspberry-pi-openjdk

**Comment by adriens** [comment]
@gbertherat , check cette image https://hub.docker.com/r/balenalib/raspberry-pi-openjdk

**Comment by gbertherat** [comment]
Le RPI ayant une architecture 32 bits, il est impossible pour lui de compiler le code

**Comment by adriens** [comment]
Yes, parfait, good job @gbertherat 
Je vais devoir investir dans un Jetson Nano 🎁
