### ISSUE TITLE
Photos de fréquentation zone avec capuche et cagoule

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#36]
Dans le cadre de #35 et #34 , fournir des photos où  une persone a une :

- [ ] capuche
- [ ] cagoule

**Comment by gbertherat** [comment]
Images prises sur internet:
https://imgur.com/a/l68SgtD

**Comment by adriens** [comment]
Excellente idée d'être aller pomper sur imgur 👏

**Comment by adriens** [comment]
Un exemple de mode debug et requête `curl` sur ce ticket 🙏
