### ISSUE TITLE
LiveCAM > Documentation

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#37]
# Action

Dans le répertoire dédié liveCAM, rédiger une doc markdown dédiée LIVECAM.md qui explique comment utiliser les script python

# Détaiils

Dans le répaertoire en question:

- [ ] Créer un vagrant file qui présintalle l'env avec Python3, avec comme os de base [bionic64](https://app.vagrantup.com/ubuntu/boxes/bionic64)
- [ ]  Créer DockerFile qui permet de faire tourner le liveCam, sur la [version alpine](frolvlad/alpine-python3)

**Comment by gbertherat** [comment]
Je ne pense pas que ça soit une bonne idée de faire un Dockerfile puisque le client doit pouvoir jouer avec les fichiers d'authentification, et les images téléchargées

**Comment by adriens** [comment]
La conf, ça se sort bien d'une image docker ;-p Ca permet da'dresser un public plus large, c'est une option, pas une obligation

**Comment by adriens** [comment]
... ensuite si pour livrer plusieurs clients, c'est mieux de packager dans une image, en termes de delivery
