### ISSUE TITLE
Script de création de CSV en sortie de LiveCAM

### ISSUE THREAD

**Issue by gbertherat** [adriens/person-counter-api#43]
Créer un script permettant de créer un CSV avec comme information la date, le nombre de personnes, le chemin de la photo et le nom du fichier
Ce CSV permettra de comparer le nombre de photo avec une (ou +) personne détectée et le nombre de photo total

**Comment by adriens** [comment]
Excellent, on va bien s'amuser à analyser ce fichier 🚀

**Comment by gbertherat** [comment]
@adriens [LiveCAM Stats.xlsx](https://github.com/adriens/person-counter-api/files/5599176/LiveCAM.Stats.xlsx)

**Comment by adriens** [comment]
:bomb:
