### ISSUE TITLE
Se déconnecter et reconnecter à chaque exécution LiveCAM

### ISSUE THREAD

**Issue by gbertherat** [adriens/person-counter-api#44]

**Comment by adriens** [comment]
Yes, ça va vraiment rendre le script robuste ✔️

**Comment by adriens** [comment]
Top, du coup c'est reparti pour laisser tourner en background ❔ afin de tester la robustesse ? 🙏

**Comment by adriens** [comment]
En attente de confiramtion de test de robustesse
