### ISSUE TITLE
Endpoint /photos/{img}/detect/full > Renvoyer un objet qui embarque la partie analyse ET metadata Tika

### ISSUE THREAD

**Issue by adriens** [adriens/person-counter-api#5]
# Description

Cf #1 , sur la partie `/photos/{img}/detect/full`, envoyer un objet composé qui embarque:

- l'analyse de l'image (classe d'objets, confiance, ...)
- les metadatas de l'image (le body de Tika)

Grâce à ça, on saura quelle version de l'image a été analysée, dans le cas où on analyserait moins vite que le rythme de dépot des photos. Ainsi, on a tout dans une seule et même réponse si on le souhaite. 

# NB

Bien noter que la réponse doit impérativement renvoyer l'analyse de l'image dont les métadtas ont été extraites. Il faut donc extraire l'image puis la traiter dans les deux chaînes, mais il est impératif que l'image ne soit chargée qu'une unique fois en mémoire et non rechargée sur disque

**Comment by adriens** [comment]
# Côté service à créer


1. Créer la méthode qui prend en input une image
2. Côté jdl : Parser l'image et récupérer l'objet de sortie
3. Côté Tika : idem que précédemment
4. Renvoyer l'object composé (via une classe que tu auras créee) qui embarque les deux objets précédents

# Controller

1. Juste appeler le service précédent

**Comment by gbertherat** [comment]
Vu les problèmes de typage, je ne pense pas que cette issue soit réalisable, ou vaille le coût. Pour l'instant, l'image est appelée deux fois, et n'est pas gardée en mémoire entre les appels.

**Comment by adriens** [comment]
Yes, je rejette 👎
